<?php
$site="//sports.sj/";
$images=$site."images/";
$login=$site."Login/";
$logout=$site."Login/logout.php";
$change=$login."change.php";
$forgot=$login."forgot.php";
$registration=$site."Registration/";
$events=$site."Events/";
$eventDetail=$events."event_details.php";
$admin=$site."Admin/";
$categories=$admin."categories.php";